### ISSUE TITLE
Iterating from the 12th to 27th sorted element

### ISSUE THREAD

**Issue by J8-8N** [mkrebser/ConcurrentSortedDictionary#2]
Hello, this great dictionary is nearly all I'd need thank you and sorry for the noob question but what would be the most efficient way to iterate from the 12th to 27th sorted elements in a dictionary of 100 elements?

This is a simple example, real numbers would be x100000ed.

As these are sorted, I thought naively that I could "for(int i=12;i<27;i++) dictionary[i]" but I assume the BTree architecture doesn't support this. So my next naive idea would be to start from the first element, iterate it 12 times, then make use of the elements until the 27th. But is there an efficient way to do this?

Thank you very much

**Comment by mkrebser** [comment]
Ah that's a good use case. I don't think the collection supports it in a very good way right now.

I might have some time in the future to make it. TBD on date.

If you are in a rush: https://github.com/mkrebser/ConcurrentSortedDictionary/blob/master/ConcurrentSortedDictionary.cs#L1703
This function would need a variant which starts the search at a specified key (rather than min/max) and then needs a condition to end early upon reaching some end value (rather than just iterating until no sibling nodes)

**Comment by mkrebser** [comment]
Hi J8-Jn, I have added range iterators. Cheers
